<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\Versioning.targets"/>
    <PropertyGroup>
        <Company>GE Aviation Systems LLC</Company>
        <Authors>$(Company)</Authors>

        <Description>Fabrica is a runtime Type Composition/Dependency Injection system for .NET-based applications.</Description>
        
        <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
        <AssemblyName>GEAviation.Fabrica</AssemblyName>
        <RootNamespace>GEAviation.Fabrica</RootNamespace>

        <PackageId>GEAviation.Fabrica</PackageId>

        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="blueprint.xsd">
            <LogicalName>GEAviation.Fabrica.blueprint.xsd</LogicalName>
        </EmbeddedResource>
    </ItemGroup>
</Project>
